theme: jekyll-theme-primer
title: Alzheimer’s Disease and Cognitive Impairment Prediction
description: CS 109 A Project
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
