theme: jekyll-theme-primer
title: Home  #Support Vector Olives
description: CS109A Group 73 Project
baseurl:
markdown: kramdown
kramdown:
    math_engine: mathjax
    input: GFM
    syntax_highlighter: rouge
